"""Pairing protocol v1: how Home Assistant hands its credentials to the app.

Versioned **separately from the health wire format** and deliberately so. The
wire protocol carries measurements and changes when the data model does; this
carries one URL and one token and changes when setup does. Tying them together
would mean a pairing fix forced a wire version bump, or worse, that a v5 wire
payload implied a v2 pairing code.

This module is the **source of truth** for the format. Home Assistant produces
pairing codes; the iOS app only ever consumes them, so there is one authoritative
implementation here and a consumer on the other side that must accept what this
produces. The client half is tested against a fixture generated by this encoder,
not against a second specification written by hand.

Security, stated plainly because the encoding invites the wrong assumption: the
payload is base64, and **base64 is not encryption**. Anyone holding the pairing
code holds the token, and the token is the only thing standing between them and
this webhook. A screenshot of the QR is a credential. It therefore must not
appear in logs, diagnostics, error messages, or a bug report - which is why
`PairingPayload.__repr__` is overridden and why nothing in this module ever
formats a token into an exception.
"""

from __future__ import annotations

import base64
import ipaddress
import json
from dataclasses import dataclass
from enum import StrEnum
from typing import Any, Final
from urllib.parse import urlsplit

#: Bumped only when the *shape* below changes. Independent of WIRE_VERSION.
PAIRING_VERSION: Final = 1

#: Custom scheme, and the secret rides in the **fragment** rather than the query.
#: A fragment is not sent to a server on an ordinary HTTP request, so a pairing
#: code that is mistyped into a browser instead of scanned does not hand the
#: token to whoever operates that host. That is a mitigation for one specific
#: mistake, not a substitute for treating the whole string as a secret.
PAIRING_SCHEME: Final = "eigenpuls"
PAIRING_ACTION: Final = "pair"


class PairingError(Exception):
    """A pairing code could not be produced or read.

    Carries a stable machine-readable reason and never the payload: an error
    string is exactly the kind of value that ends up in a log.
    """

    def __init__(self, reason: str) -> None:
        super().__init__(reason)
        self.reason = reason


class Reach(StrEnum):
    """Whether this connection is expected to work away from home.

    Recorded honestly rather than optimistically. A local URL genuinely does not
    work on mobile data, and a setup flow that implies otherwise produces a
    person who thinks the app is broken.
    """

    #: Reachable from anywhere - a cloudhook, or an external HTTPS endpoint.
    REMOTE = "remote"
    #: Reachable only on the home network.
    LOCAL = "local"


def is_cleartext_allowed(url: str) -> bool:
    """Whether plain HTTP may be used for this target.

    iOS permits cleartext to private addresses without an ATS exception - that
    was measured on a real device, not assumed - but it will just as happily
    send cleartext to a public host. iOS is not the guard here; this is. The
    rule is deliberately about *where the target is*, not about what the person
    ticked in a settings screen.

    Allowed: RFC1918 IPv4, IPv6 unique-local, and ``.local`` names. Everything
    else is refused, including two that look private and are not useful:

    * **loopback** - reachable by Home Assistant, never by the phone. Allowing
      it would produce a pairing code that cannot possibly work.
    * **link-local** - means no DHCP, which is not a home network anyone pairs
      against, and is exactly the address family that contaminated the P3
      routing measurement.
    """
    host = urlsplit(url).hostname
    if not host:
        return False

    if host.endswith(".local"):
        return True

    try:
        address = ipaddress.ip_address(host)
    except ValueError:
        # A real hostname. It may well resolve to a private address, but this
        # runs on Home Assistant and the phone resolves it somewhere else -
        # possibly to something public. Not guessable from here, so refused.
        return False

    if address.is_loopback or address.is_link_local:
        return False
    return address.is_private


def is_usable_target(url: str) -> bool:
    """Whether a URL may be handed to the app at all.

    HTTPS is accepted wherever it points: the certificate is the phone's to
    validate, and it will refuse a self-signed one on its own (measured: -1202).
    HTTP is accepted only where cleartext is allowed.
    """
    parts = urlsplit(url)
    if not parts.hostname:
        return False
    if parts.scheme == "https":
        return True
    if parts.scheme == "http":
        return is_cleartext_allowed(url)
    return False


@dataclass(frozen=True, slots=True)
class PairingPayload:
    """Everything the app needs to start delivering, and nothing else.

    No device identifier, no account, no installation id, no health data. Each
    would be a thing to justify later; none is needed to POST to a URL with a
    token.
    """

    url: str
    token: str
    reach: Reach
    version: int = PAIRING_VERSION

    def __repr__(self) -> str:
        """Never render the token.

        A dataclass repr is how a secret reaches a log without anybody deciding
        to put it there.
        """
        return (
            f"PairingPayload(version={self.version}, url={self.url!r}, "
            f"reach={self.reach.value!r}, token=<redacted>)"
        )

    def to_uri(self) -> str:
        """The string that goes into the QR code and the copy field."""
        body = {
            "v": self.version,
            "url": self.url,
            "token": self.token,
            "reach": self.reach.value,
        }
        raw = json.dumps(body, separators=(",", ":"), sort_keys=True).encode()
        encoded = base64.urlsafe_b64encode(raw).decode().rstrip("=")
        return f"{PAIRING_SCHEME}://{PAIRING_ACTION}#{encoded}"


def encode(url: str, token: str, reach: Reach) -> str:
    """Produce a pairing code, refusing to encode one that cannot work.

    Validation belongs here rather than at the call site: a pairing code is
    handed to a person who will scan it before anyone discovers the target was
    unusable, and the failure would surface on the phone as a sync error with
    no obvious cause.
    """
    if not token:
        raise PairingError("missing_token")
    if not is_usable_target(url):
        raise PairingError("unusable_url")
    return PairingPayload(url=url, token=token, reach=reach).to_uri()


def decode(uri: str) -> PairingPayload:
    """Read a pairing code.

    Present so the format has one implementation that round-trips, and so the
    tests exercise the same parsing rules the Swift consumer has to implement.
    Home Assistant itself never needs to decode one.
    """
    parts = urlsplit(uri)
    if parts.scheme != PAIRING_SCHEME or parts.netloc != PAIRING_ACTION:
        raise PairingError("bad_scheme")
    if not parts.fragment:
        raise PairingError("missing_payload")

    padded = parts.fragment + "=" * (-len(parts.fragment) % 4)
    try:
        body: Any = json.loads(base64.urlsafe_b64decode(padded))
    except (ValueError, TypeError) as err:
        raise PairingError("malformed_payload") from err

    if not isinstance(body, dict):
        raise PairingError("malformed_payload")

    version = body.get("v")
    if not isinstance(version, int) or isinstance(version, bool):
        raise PairingError("missing_version")
    if version != PAIRING_VERSION:
        # Named distinctly from a malformed payload on purpose: the app can tell
        # the person their app is too old to read this code, which is actionable,
        # instead of "the code is broken", which is not.
        raise PairingError("unsupported_pairing_version")

    url = body.get("url")
    if not isinstance(url, str) or not url:
        raise PairingError("missing_url")
    token = body.get("token")
    if not isinstance(token, str) or not token:
        raise PairingError("missing_token")

    try:
        reach = Reach(body.get("reach"))
    except ValueError as err:
        raise PairingError("bad_reach") from err

    if not is_usable_target(url):
        raise PairingError("unusable_url")

    return PairingPayload(url=url, token=token, reach=reach, version=version)
